Repository kubeflow/blog, pull requests merged in 2020-11, with the labels that each got.

#58 1.2 Blog Post
  _posts/2020-11-18-kubeflow-1.2-blog-post.md
Labels: cla: yes, size/L

#59 Revert "1.2 Blog Post"
  _posts/2020-11-18-kubeflow-1.2-blog-post.md
Labels: cla: yes, size/L

#60 1.2 Blog Post
  _posts/2020-11-18-kubeflow-1.2-blog-post.md
  images/2020-11-18-kubeflow-1-2-announcement/kfp-tekton-support.png
Labels: cla: yes, size/L

#63 Minor changes to the 1.2 blog post
  _posts/2020-11-18-kubeflow-1.2-blog-post.md
Labels: cla: yes, size/S

#61 Update Jeffwan’s company name and add more details for WG-training
  _posts/2020-11-18-kubeflow-1.2-blog-post.md
Labels: cla: yes, size/XS

#62 Fix OWNERS file
  OWNERS
Labels: cla: yes, do-not-merge/invalid-owners-file, lgtm, size/XS
