Repository kubeflow/blog, pull requests merged in 2020-08, with the labels that each got.

#38 Add a small meme for twitter cards.
  _posts/2020-08-01-data-science-meets-devops.md
  images/2020-08-01-data-science-meets-devops/smallmeme.png
Labels: cla: yes, size/XS

#39 Add a new version of the small meme.
  images/2020-08-01-data-science-meets-devops/smallmeme.png
Labels: cla: yes, size/XS

#40 Cicd blog
  images/2020-08-01-data-science-meets-devops/smallmeme.png
Labels: cla: yes

#44 Update 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes, size/S

#45 Update 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes, size/XS

#46 Update 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes, size/XS

#47 Update 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes, size/S

#50 Clarify the review process for blogs
  OWNERS
  README.md
Labels: approved, cla: yes, lgtm, size/S
