Repository kubeflow/blog, pull requests merged in 2020-07, with the labels that each got.

#10 add links to author names
  _posts/2020-03-16-mpi-operator.md
Labels: cla: yes

#11 enable comments
  _posts/2020-03-02-kubeflow-1-0-cloud-native-ml-for-everyone.md
  _posts/2020-03-16-mpi-operator.md
  _posts/2020-07-10-kubeflow-kale.md
Labels: cla: yes

#9 update README with instructions
  README.md
Labels: cla: yes

#19 Update index.html for twitter preview cards
  index.html
Labels: cla: yes

#20 Fix Netlify URL Link
  .github/workflows/chatops.yaml
Labels: cla: yes

#21 Add google analytics
  _config.yml
Labels: cla: yes

#18 kubeflow 1.1 blog post
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: no

#22 Revert "kubeflow 1.1 blog post"
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes

#23 Update 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes

#25 Correct Typos 2020-07-31-kubeflow-1.1-blog-post.md
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes

#26 Update the about page
  _pages/about.md
Labels: cla: yes

#30 Hide KF 1.1 Blog Post Per Request of Josh Bottum
  _posts/2020-07-31-kubeflow-1.1-blog-post.md
Labels: cla: yes

#36 Update the google analytics id to be a new property.
  _config.yml
Labels: cla: yes, lgtm, size/XS

#37 Fix local permissions issue
  docker-compose.yml
Labels: cla: yes, size/XS
