Repository kubeflow/blog, pull requests merged in 2021-02, with the labels that each got.

#67 Adding more OWNERS
  OWNERS
Labels: cla: yes, size/XS

#65 KFServing v0.5 Announcement Blog
  .DS_Store
  _posts/2020-02-23-kfserving-0.5.md
  images/2020-02-23-kfserving-0.5/image1.png
  images/2020-02-23-kfserving-0.5/image2.png
  images/2020-02-23-kfserving-0.5/image3.png
  images/2020-02-23-kfserving-0.5/image4.png
  images/2020-02-23-kfserving-0.5/image5.png
Labels: approved, cla: yes, lgtm, size/M

#69 change blog publish date
  .DS_Store
  _posts/2021-03-08-kfserving-0.5.md
  images/2021-03-08-kfserving-0.5/image1.png
  images/2021-03-08-kfserving-0.5/image2.png
  images/2021-03-08-kfserving-0.5/image3.png
  images/2021-03-08-kfserving-0.5/image4.png
  images/2021-03-08-kfserving-0.5/image5.png
Labels: approved, cla: yes, lgtm, size/S
