Repository kubeflow/blog, pull requests merged in 2022-10, with the labels that each got.

#121 Add blog post about 2022 survey results
  _posts/2022-08-19-kubeflow-user-survey-2022.md
  images/2022-08-19-kubeflow-user-survey-2022/demographics-industry.png
  images/2022-08-19-kubeflow-user-survey-2022/demographics-title.png
  images/2022-08-19-kubeflow-user-survey-2022/documentation-word-cloud.png
  images/2022-08-19-kubeflow-user-survey-2022/gaps-in-ml-activities-and-workflow.png
  images/2022-08-19-kubeflow-user-survey-2022/kubeflow-gaps.png
  images/2022-08-19-kubeflow-user-survey-2022/ml-task-time-consuming-challenging.png
Labels: lgtm, approved, size/L

#130 Adding blog on KF application to CNCF
  _posts/2022-10-24-kubeflow-applied-cncf-incubating.md
Labels: lgtm, approved, size/M

#108 Fix typo in kfserving transition blog
  _posts/2021-09-27-kfserving-transition.md
Labels: cla: yes, lgtm, approved, size/XS
