Repository kubeflow/blog, pull requests merged in 2025-07, with the labels that each got.

#172 Remove redundant blog post title from the fraud detection article
  _posts/2025-07-15-fraud-detection-e2e.md
Labels: lgtm, approved, size/XS

#169 blog: Add post on introducing Kubeflow Trainer V2
  .gitignore
  _posts/2025-07-09-introducing-trainer-v2.md
  images/2025-07-09-introducing-trainer-v2/MPI-support.drawio.svg
  images/2025-07-09-introducing-trainer-v2/runtimes.png
  images/2025-07-09-introducing-trainer-v2/trainer-pipeline-framework.drawio.svg
  images/2025-07-09-introducing-trainer-v2/trainerv2.png
  images/2025-07-09-introducing-trainer-v2/user-personas.drawio.svg
Labels: lgtm, approved, size/L

#174 blog: Change the date of trainer v2 blog
  _posts/2025-07-21-introducing-trainer-v2.md
  images/2025-07-21-introducing-trainer-v2/MPI-support.drawio.svg
  images/2025-07-21-introducing-trainer-v2/runtimes.png
  images/2025-07-21-introducing-trainer-v2/trainer-pipeline-framework.drawio.svg
  images/2025-07-21-introducing-trainer-v2/trainerv2.png
  images/2025-07-21-introducing-trainer-v2/user-personas.drawio.svg
Labels: lgtm, approved, size/S
